### ISSUE TITLE
a bug, an oddity and two requests

### ISSUE THREAD

**Issue by SebiTimeWaster** [Allen0246/modrinth_updater#1]
the bug: 
in the file `/modrinth_updater/config.py` you check `if not env_mc_path`, but it should check if env_mc_path is not `None` (seemingly the default in the .env file), so at the moment the .env config option is always ignored.
additionally in the same file you assume that everyone uses windows (by only checking for the appdata directory), but it should be easy to accomodate macos/linux also, im sure there are guides online. btw otherwise your app works fine under linux, i just specified the correct folder in the .env file.

the oddity:
i had two fabric launchers installed, 1.21.5 and 1.21.6 and it took the older one to check for updates, i think it should be the newer one or better let the user decide.

request #1:
when no update is available you move the resources out into the "wait for update" folders, which is often not necessary and i will move them back in to see if it will work anyway, so it just creates manual work for me. especially resourcepacks and shaderpacks rarely have breaking dependencies with newer versions, so i would move them back in and everything works 90% of the time. some mods also only update when something breaks, so mods that are listed for 1.21.1 work on 1.21.6 and will not update to explicitly show they work on 1.21.6.
maybe it would be better to have a separate output after the run that explicitly lists all resources that could not be updated so the user knows what resources to check/move out if something crashes/breaks?

request #2:
add a "dry run" option so one can simulate what it would do without changing any files.

other than that: really nice app!

**Comment by SebiTimeWaster** [comment]
i just tried the main version from 2 days ago and found a bug, it says:
`Your loader is fabric-None.`
and it updated a couple of mods to the 1.21.7 version which is higher than my installed fabric 1.21.6 version.

**Comment by Allen0246** [comment]
Thanks for your comment! Now it should be fine. Also added to be able to jump back a previous version, like if you have a mod installed as 1.21.7 it will download back the to 1.21.6 (your loader version) .
I put all of the files inside a wait_for_update folder, because if you have 2 different version of a mod it can conflict with the other.
For shaders and resourcepacks it can work with not the latest version, although its better if you use the latest of them. I will  make an option to disable moving these files to a other folder.

**Comment by SebiTimeWaster** [comment]
please add that option also for mods themselfs, that way the user can decide what they want to do, thank you

**Comment by SebiTimeWaster** [comment]
new bug: the newest version of the script moved `litematica-fabric-1.21.8-0.23.3.jar` out as incompatible, i presume its because it is marked as `1.21.6-1.21.8` and the script thought it is 1.21.8 only... i have no clue how this could be solved, unless you can look into the jar file...

**Comment by Allen0246** [comment]
I checked the bug ( with 1.26 and 1.28 ) which you mentioned, but it work fine for me.
Did you install the malilib dependence mod? Its need to run the litematica mod.
https://modrinth.com/mod/malilib?version=1.21.6&loader=fabric
Also there is a little problem with my algorithm, i didn't check if there is any dependence when the mod update happen, i planing to implement that too.
After i implemented the datapacks update, i will implement the dependence checker, then refactor the whole project and implement the things which you mentioned first the option to turn on/off moving mods,sharders etc... and the dry run.

**Comment by SebiTimeWaster** [comment]
yeah, all dependencies are installed and correct... i dont know, maybe it was caused by an earlier version... ill keep an eye on it.

one thing that can be optimised but is not super important is that mods/etc that are moved into the "wait for updates" folders are checked twice, once before they are moved out, then again when the whole folder is checked afterwards. simply moving the "wait for updates" check before the main check would solve that i think.

the dry run is by far the most unimportant thing i would say, its just nice to have when you are testing a new tool and are unsure if you want to use it. i personally would implement it as an argument, i.e. `python3 tool -d`

**Comment by SebiTimeWaster** [comment]
it still happens (newest version):

<img width="805" height="36" alt="Image" src="https://github.com/user-attachments/assets/122cfac9-6668-4cbf-84e3-78be6a9f91de" />

the mod is compatible with 1.21.6:

<img width="867" height="68" alt="Image" src="https://github.com/user-attachments/assets/11af5f47-2cbd-4982-8619-1e6d74d14902" />

**Comment by Allen0246** [comment]
okay, now probably got it. It was a version comparing issue, now should work fine.

<img width="757" height="32" alt="Image" src="https://github.com/user-attachments/assets/a24c2ae5-362b-4951-b25c-186b4f5e2939" />

**Comment by SebiTimeWaster** [comment]
unfortunately still happens for me, is maybe not everything commited/pushed?

**Comment by Allen0246** [comment]
please try again now. 
I did a clean clone from the latest commit, and it work fine for me even if i just have the litematica and the fabric mod in the mods folder. 

<img width="781" height="92" alt="Image" src="https://github.com/user-attachments/assets/ffc040dd-d22d-4f81-a6e3-8509a33889ac" />

**Comment by SebiTimeWaster** [comment]
i never experienced that a software problem was solved by cloning anew, but i tried it and the result is still the same:

<img width="806" height="43" alt="Image" src="https://github.com/user-attachments/assets/14b9c41c-1d7a-4c36-bd07-5f2837c09d10" />

i even tried to move all other mods out except litematica and malilib to match your screenshot, still the same.

is there maybe an OS dependent switch in the code?

**Comment by Allen0246** [comment]
It should be some kind of OS issue. It probably hashing wrong the jar file and cant find it with the modrinth API. What kind of OS are you using, i will try to debug the problem.

**Comment by SebiTimeWaster** [comment]
No, its not an OS issue. you mentioning hashing made me compare hashes between the jar i have on disk and a newly downloaded one, and they differ.

<img width="816" height="34" alt="Image" src="https://github.com/user-attachments/assets/75c4ba33-80e2-40a3-b02b-58cbe463a047" />

<img width="816" height="38" alt="Image" src="https://github.com/user-attachments/assets/0d0f172a-ab57-4f8b-bf57-6866c9bc35ca" />

i cant say why, maybe the mod creator updated the version without bumping the version numbers, maybe one of them is infected, i dont know.

i guess a hash is not a good comparison in this case...

**Comment by SebiTimeWaster** [comment]
i was right, the mod creator changed 2 translation lines without bumping the version number.

a diff over both unzipped jars reveals:
```
diff -r litematica-fabric-1.21.8-0.23.3/assets/litematica/lang/zh_cn.json litematica-fabric-1.21.8-0.23.3_/assets/litematica/lang/zh_cn.json
740,741c740,741
<     "litematica.gui.label.replace_behavior.none": "只能粘贴到空位",
<     "litematica.gui.label.replace_behavior.with_non_air": "粘贴全部非空气方块",
---
>     "litematica.gui.label.replace_behavior.none": "无(只能粘贴到空气的位置)",
>     "litematica.gui.label.replace_behavior.with_non_air": "粘贴所有非空气方块",
```

**Comment by Allen0246** [comment]
Can you attach here the infected version and i try to figure out something how to avoid that.

**Comment by SebiTimeWaster** [comment]
here is the "old version" of litematica. i had to rename .jar to .zip since github doesnt let me upload jar files, please do the reverse.

[litematica-fabric-1.21.8-0.23.3.zip](https://github.com/user-attachments/files/21824505/litematica-fabric-1.21.8-0.23.3.zip)

**Comment by SebiTimeWaster** [comment]
main seems to be broken at the moment:

```
❗️ Checking updateable mods in the wait_for_update folder...
Traceback (most recent call last):
  File "/home/minecraft/modrinth_updater/main.py", line 128, in <module>
    update()
  File "/home/minecraft/modrinth_updater/main.py", line 69, in update
    wait_for_update_mod = check_wait_for_update_mods(mod_file, loader_version, loader)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minecraft/modrinth_updater/modrinth_updater/services/mods.py", line 88, in check_wait_for_update_mods
    version, response_status_code = get_local_version(mod_path, game_versions)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

do you know how/why to work on branches?

**Comment by Allen0246** [comment]
Sorry for the waiting time, i was on a vacation. Now should be good, yea i used branches before but i never thought there will be someone who give feedback about the project, and i am very glad you do! 
I will make a beta or test branch when i can test those things before something bad happen like this.

**Comment by SebiTimeWaster** [comment]
i hope your vacation was nice :)

<img width="1046" height="20" alt="Image" src="https://github.com/user-attachments/assets/e29d2349-9f07-457c-bc13-6b71157ce59f" />

Cool that it shows that, but what mod is that? i have > 30 mods, a filename would be nice :)

**Comment by Allen0246** [comment]
ohh yes you right, added that small fix.

**Comment by SebiTimeWaster** [comment]
hm... i think i found a bug, malilib was not updated (the script showed it as up-to-date):

<img width="1413" height="552" alt="Image" src="https://github.com/user-attachments/assets/db6263c7-b5d0-4cf2-8fa4-fd636c3b7911" />

<img width="812" height="18" alt="Image" src="https://github.com/user-attachments/assets/52de8fe5-bc67-49af-8294-546961fdc277" />

i updated it by hand and it works.

**Comment by Allen0246** [comment]
thanks, now it should work, I implemented the correct version check.
